### ISSUE TITLE
xhr requests not captured

### ISSUE THREAD

**Issue by SmartManoj** [peace-maker/copy-as-python-requests#3]
![image](https://user-images.githubusercontent.com/7231077/192083702-54af8544-d9ab-4548-8593-5f41eff8d777.png)

**Comment by peace-maker** [comment]
`No devtools window open` happens when the extension missed the `open` event of the devtools. Since there is no api to poll for the devtools window of a tab there is no way to recover from that. The extension must receive the event sent when opening the devtools to save a handle to it.

A workaround until the webextension api gets more stable is to close and reopen the devtools..

**Comment by peace-maker** [comment]
I've found a way to work around the problem. Please have a try with version 1.1 again.
